# Generated by Django 4.1.2 on 2023-01-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Macam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Garam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koordinat', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=60)),
                ('tahun_2017', models.IntegerField(null=True)),
                ('tahun_2018', models.IntegerField(null=True)),
                ('tahun_2019', models.IntegerField(null=True)),
                ('tahun_2020', models.IntegerField(null=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uaspbo_app.jenis')),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publikasi', models.DateField(null=True)),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=40, null=True)),
                ('macam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uaspbo_app.macam')),
            ],
        ),
    ]
